export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_REDIRECT = 'SET_REDIRECT'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const CREATE_SOCKET_SUCCESS = 'CREATE_SOCKET_SUCCESS'
export const CREATE_SOCKET_FAIL = 'CREATE_SOCKET_FAIL'
export const CREATE_SOCKET_START = 'CREATE_SOCKET_START'